// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package v1

import (
	"time"
)

type GroceryItem struct {
	ID            int64
	GroceryListID int64
	Name          string
	Quantity      int32
	Checked       bool
	CreatedAt     time.Time
	Version       int32
}

type GroceryList struct {
	ID        int64
	Name      string
	CreatedAt time.Time
	Version   int32
}
