name: Proto

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Buf
        uses: bufbuild/buf-setup-action@v1

      - name: Lint proto files
        uses: bufbuild/buf-lint-action@v1
